### ISSUE TITLE
missing log lines

### ISSUE THREAD

**Issue by faryon93** [logdna/logspout#6]
Hi,
it seems logspout is not able to capture all logs produced by docker. From time to time some log lines are missing in LogDNA.

If I choose INACTIVITY_TIMEOUT=5s all logs make it through, but every ~5s the CPU usage spikes at 100% due to docker parsing all logfiles (see gliderlabs/logspout#246). 
Setting TAIL=0  is resulting in lower CPU usage, but some log lines are missing.

All containers are running on a Docker Swarm cluster.
Docker: 18.09.1
Docker log-driver: json-file
logspout: v3.2.6-custom (https://hub.docker.com/r/logdna/logspout)

Do you hav any idea how to properly send all log lines without risking high CPU usage? Or is there another way to get Docker Swarm container logs to LogDNA?

Kind regards,
Maxi

**Comment by smusali** [comment]
@faryon93, sorry for the very late response!

Missing logs might be happening due to the lack of stability during that time. Since last year we have improved it a lot and recently released [the newest and more stable `LogDNA LogSpout v1.2` image](https://hub.docker.com/r/logdna/logspout).

Please, let us know if you are still having the same issue.
